import images from "src/Importer/Importer"
export const ImageBoxData=[
    {
        id:1,
        title:"",
        text:"",
        image:`${images['Home/1.png']}`,
    },
    {
        id:2,
        title:"",
        text:"",
        image:`${images['Home/2.png']}`,
    },
    {
        id:3,
        title:"",
        text:"",
        image:`${images['Home/3.png']}`,
    },
    {
        id:4,
        title:"",
        text:"",
        image:`${images['Home/4.png']}`,
    },
    {
        id:5,
        title:"",
        text:"",
        image:`${images['Home/5.png']}`,
    },
    {
        id:6,
        title:"",
        text:"",
        image:`${images['Home/6.png']}`,
    },
    {
        id:7,
        title:"",
        text:"",
        image:`${images['Home/7.png']}`,
    },
    {
        id:8,
        title:"",
        text:"",
        image:`${images['Home/8.png']}`,
    },
    {
        id:9,
        title:"",
        text:"",
        image:`${images['Home/9.png']}`,
    },
    {
        id:10,
        title:"",
        text:"",
        image:`${images['Home/10.png']}`,
    },
    {
        id:11,
        title:"",
        text:"",
        image:`${images['Home/11.png']}`,
    },
    {
        id:12,
        title:"",
        text:"",
        image:`${images['Home/12.png']}`,
    },
]